package models

// Code generated by TORM; DO NOT EDIT.

import (
	"github.com/google/uuid"
	"time"
)

type Creator struct {
	id        uuid.UUID
	username  string
	email     string
	createdAt time.Time
	updatedAt time.Time
}
