package models

// Code generated by TORM; DO NOT EDIT.

import (
	"time"
)

type Creator struct {
	id        string
	firstName string
	lastName  string
	email     string
	createdAt time.Time
	updatedAt time.Time
	Posts     []Post
}
