package models

// Code generated by TORM; DO NOT EDIT.

import (
	"time"
)

type Post struct {
	id        string
	title     string
	content   string
	published bool
	createdAt time.Time
	updatedAt time.Time
	authorId  string
	author    Creator
}
