package models

// Code generated by TORM; DO NOT EDIT.

import (
	"github.com/google/uuid"
	"time"
)

type Post struct {
	id        uuid.UUID
	title     string
	content   string
	published bool
	createdAt time.Time
	updatedAt time.Time
	authorId  string
}
