name: Create Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'Release ')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract version from commit message
        id: extract_version
        run: echo "::set-output name=version::$(echo ${GITHUB_EVENT_HEAD_COMMIT_MESSAGE} | sed -n 's/^Release \(.*\)$/\1/p')"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: ${{ contains(steps.extract_version.outputs.version, '-alpha') || contains(steps.extract_version.outputs.version, '-beta') }}